### ISSUE TITLE
Manually inputting Lvl Min/Max values outside of difficulty scale crashes the app

### ISSUE THREAD

**Issue by prohibited-props** [noahm/DDRCardDraw#105]
**Summary:**
Manually inputting Lvl Min/Max values outside of difficulty scale (1-19) crashes the app

**Steps to reproduce:**
1. Open Card Draw Options
2. Do either of the following:
- Change the value of Lvl Min to a number higher than Lvl Max and greater than 19
- Clear the Lvl Max field altogether
- Enter a plus or minus character in either field
4. Screen goes blank (or displays stack trace in development mode)

Error message:
`Error: [Blueprint] clamp: max cannot be less than min`
![image](https://user-images.githubusercontent.com/108554718/198189599-3696245f-ccd0-412a-a56f-f2ee493e55e0.png)

**Additional notes:**
I don't think it's a common scenario, but it might be inconvenient for someone to reload the entire page if they accidentally trigger this. Not sure of a good solution for this. (Pop up error message? Auto change value? Block manual input altogether?)

**Comment by noahm** [comment]
This is now fixed in 7ca2fc25e32ca2a2f59b1ee98f8b3473434fe263

Thanks for the report!
