### ISSUE TITLE
Reborn Magic wrong difficulty level

### ISSUE THREAD

**Issue by FuriousDCSL** [noahm/DDRCardDraw#2]
REBORN MAGIC seiya-murai meets "eimy" Expert listed as 10, it is a 9 in
 DDR A.

![image](https://user-images.githubusercontent.com/39023936/46900310-e804bf00-ce54-11e8-8141-5a4009ba5daa.png)
 
![image](https://user-images.githubusercontent.com/39023936/46900347-66616100-ce55-11e8-8c89-7b3c2b0ee986.png)

**Comment by noahm** [comment]
Just deployed a fix. Thanks for the report!
