### ISSUE TITLE
Feature Request - "Clear" Button to Clear All On-Screen Draws While Persisting Card Draw Options

### ISSUE THREAD

**Issue by rocopltx** [noahm/DDRCardDraw#206]
### Context

Currently, given I have card draws on screen and I want to clear the screen of previous draws to remove visual clutter, when I do so, then I must either refresh the page or open a new tab.

Although when I do so in those ways, I'm successful and get a cleared screen, my card draw options do **not** persist, and I have to either reload the JSON file or manually re-program the card draw options before continuing, briefly interrupting focus while TO'ing.

An on-site "Clear" button (or GUI equivalent in menus, as appropriate) that clears the screen of prior draws while persisting the card draw options would be a QoL improvement to TO's who, for example, want to show card draws to players only one pools round or even only one match at a time.

### The Feature Request

Given I have card draws on-screen,
  and I want to clear the screen of previous draws to remove visual clutter,
When I hit a "Clear" button on-screen or hidden somewhere easily reachable in the website's GUI,
Then all on-screen draws disappear from screen,
  and all card draw options persist (i.e. they do not reset to defaults).

**Comment by noahm** [comment]
You make a great case for why this is a valuable thing to add! I'll try to have that added sometime in the next few days.

**Comment by noahm** [comment]
This now lives in the hamburger menu! (top left corner)
