### ISSUE TITLE
Bug - When Loading Consecutive JSON Files, "groupSongsAt" is Enabled While Null

### ISSUE THREAD

**Issue by rocopltx** [noahm/DDRCardDraw#207]
(Context: following along to https://www.browserstack.com/guide/how-to-write-a-bug-report)
### Environment
This bug occurs on the live build of ddr.tools

### Steps to reproduce a Bug
1. Visit ddr.tools
2. Access the card draw settings, and click "Load".
3. Load a JSON file containing the following JSON body (I'll leave it in a comment) that has **configState.groupSongsAt** set to **null**.
4. While those settings are configured, load _another_ JSON file containing the following body that also has **configState.groupSongsAt** set to **null**. (I'll leave it in a comment)

### Expected Result
* From default, when loading the first JSON file, as expected, "Group top end charts starting at" is **disabled** in the Web GUI.
* And, when loading the second file after the first, that option is also **disabled**.

### Actual Result
* From default, loading the first JSON file, as expected, has "Group top end charts starting at" **disabled**.
* However, when loading the second file after the first, "Group top end charts starting at" is **enabled**.
    
### Visual Proof (screenshots, videos, text) of Bug
1. From default, after loading the first JSON file with "groupSongsAt" set to "null":
![image](https://github.com/noahm/DDRCardDraw/assets/107084083/5094150a-a43c-411a-a521-040e07db529f)
2. With the 1st file loaded, after loading the second file with "groupSongsAt" set to "null":
![image](https://github.com/noahm/DDRCardDraw/assets/107084083/753706fb-dd2a-4d5f-b819-3d9b37f2611c)

### Severity/Priority
Low. It is easily remedied by toggling the box manually, but in the ideal of a plug-and-play card draw setup experience, it is a minor but still present inconvenience that can add up to potential errors and otherwise a headache in longer tournaments.

**Comment by rocopltx** [comment]
### 1st JSON Loaded from Default
`
{
  "version": 1,
  "dataSetName": "a20plus",
  "configState": {
    "chartCount": 5,
    "upperBound": 12,
    "lowerBound": 10,
    "useWeights": true,
    "hideVetos": false,
    "orderByAction": true,
    "weights": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      1,
      2,
      2
    ],
    "groupSongsAt": null,
    "forceDistribution": true,
    "constrainPocketPicks": true,
    "style": "single",
    "difficulties": [
      "expert",
      "challenge",
      "difficult"
    ],
    "flags": [
      "shock"
    ],
    "showPool": false,
    "playerNames": [],
    "tournamentRounds": [
      "Pools Level 1"
    ],
    "showLabels": true
  }
}
`

**Comment by rocopltx** [comment]
### 2nd JSON After Loading First
```
{
  "version": 1,
  "dataSetName": "a20plus",
  "configState": {
    "chartCount": 5,
    "upperBound": 13,
    "lowerBound": 11,
    "useWeights": true,
    "hideVetos": false,
    "orderByAction": true,
    "weights": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      1,
      2,
      2
    ],
    "groupSongsAt": false,
    "forceDistribution": true,
    "constrainPocketPicks": true,
    "style": "single",
    "difficulties": [
      "expert",
      "challenge",
      "difficult"
    ],
    "flags": [
      "shock"
    ],
    "showPool": false,
    "playerNames": [],
    "tournamentRounds": [
      "Pools Level 2"
    ],
    "showLabels": true
  }
}
```

**Comment by noahm** [comment]
That particular setting is a bit of an odd one and I'm not surprised to see something like this pop up. I'll try to repro and fix ASAP! (thanks for taking the time to give such a detailed writeup!)

**Comment by noahm** [comment]
This ended up being a lot sneakier than I expected! The component library I use was producing phantom change events while loading settings!
