### ISSUE TITLE
Weighted difficulty instantly resets null value to 1

### ISSUE THREAD

**Issue by phuzion** [noahm/DDRCardDraw#23]
**Summary:**
When using the Weighed Distributions option, erasing the value in a field automatically sets the value to 1. This is a minor inconvenience when attempting to quickly change between tiers in a tournament. As a result, you need to enter the weight, and then erase the 1 at the beginning of it. This is more obvious on mobile devices (Card draw was done on two iPads during DDR A at RAJ this year).

**Steps to reproduce:**
* Select your difficulty range
* Check "Use Weighted Distributions"
* Erase the value of one of the fields

**Expected result:**
The field should remain blank so the user can enter a number.

**Actual result:**
The field is automatically reset to 1.

**Additional notes:**
Please see [this video](https://www.youtube.com/watch?v=PScQyCZ4pcc) demonstrating the bug on an iPhone.

**Comment by noahm** [comment]
Thanks for reporting. Just shipped a minor adjustment to coerce empty values to 0 instead of 1, so the behavior in this scenario should be much closer to expected. (won't remain blank, but allows typing a number as if it were)

**Comment by phuzion** [comment]
Tested it out on my iPhone and iPad, and it works wonderfully! Thank you!
