### ISSUE TITLE
Group bottom end charts

### ISSUE THREAD

**Issue by zeo210** [noahm/DDRCardDraw#275]
Similar to the existing "Group top end charts" functionality, add functionality to be able to group the bottom end charts as well in a way that both the "Group top end charts" and "Group bottom end charts" functionality can be used at the same time.

**Comment by chezmix** [comment]
Is this issue still relevant? I don't see the "Group top end charts" option anymore on the settings.

**Comment by noahm** [comment]
Yeah, I guess not. "Group top end" got removed when I added the option to force the number of buckets which can sort of let you do both but it's also less flexible in some ways too. I think we can close this for now in the absence of a more specific need.
