### ISSUE TITLE
DDR World Songlist Request

### ISSUE THREAD

**Issue by emcatmeow** [noahm/DDRCardDraw#351]
Hello! We are running a DDR World tournament next weekend and wanted to ask if it would be possible to add in World songs before then? Thanks so much!

**Comment by noahm** [comment]
Yes, I have a backlog of data updates I need to attend to, and I'll try to get World and Pump Phoenix ready to go later this weekend at least

**Comment by emcatmeow** [comment]
Thanks so much! Appreciate it :)

**Comment by noahm** [comment]
Pump and SMX should be up to date here in about 5 minutes. DDR World is going to be a bigger project, but I'll dig in probably sunday sometime.

**Comment by ranatalus** [comment]
@noahm The rules post for Midsummer Melody has up-to-date info on the status of everything pre-world: https://docs.google.com/document/d/16ueRKNN8kaJsS9gFER4b9-qNSdFD1jkpWS0xvtjzhW8/edit#heading=h.wb6niy5lbfl

Essentially, any tag other than "DDR GRAND PRIX music packs" should be removed from everything A3 and older except for the Triple Tribe songs (3y3s, Ambivalent Vermillia, C-C-C-N-N-N, DIABLOSIS:NAGA, suspicions, コメット⇒スケイター) which should be marked both 20th Gold Cab Exclusive and Formerly Unlockable.

Additionally, the BPL S2 songs will be unlocking for everyone July 31st (Aria, Rise as One, Drive Away, Chromatic Burst, Glow the Crown, Smash, Complete Game Victory, Abrupt Madness, Breaking the Future challenge charts) if you want to get that ready too.

Let me know if there's any way I can help!

**Comment by noahm** [comment]
@ranatalus this comment actually landed with perfect timing! I just finished cleaning up a full migration of existing A3 data merged into the latest World songs and was just started to make a final pass over all the flags (tags) to remove the ones that don't make sense anymore. Look for the new update here in the next few hours!

**Comment by noahm** [comment]
DDR World data is now available in the app, and the next wave of GP unlocks is prepped over in #353 (current set of GP flags may still be out of date, so I'll go over it all one more time too)

**Comment by emcatmeow** [comment]
Thank you so much!!!
